FROM mcr.microsoft.com/azure-cli

# Download terraform for linux
RUN wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip

# Unzip
RUN unzip terraform_0.14.7_linux_amd64.zip

# Move to local bin
RUN mv terraform /usr/local/bin/
# Check that it's installed
RUN terraform --version